export * from "./ModalPriceData"
export * from "./CompletedProjectsData"
export * from "./ModalReviewsData"
export * from "./WhyUsData";
export * from "./SolutionCatalogData";
export * from "./ModalCertificatesData";
export * from "./SolutionCatalogCheckData";
export * from "./PhotoGalleryData";
export * from "./FunctionalityOptionsData";
export * from "./FunctionalityCardData";
export * from "./ServiceData";
export * from "./AdditionalServicesCardData";
export * from "./WarrantyData";