export * from "./Main";
export * from "./CompletedProjects";
export * from "./WhyUs";
export * from "./SolutionCatalog";
export * from './PhotoGallery';
export * from "./Functionality";
export * from "./AdditionalServices";
export * from "./Production";
export * from "./Service";
export * from "./Warranty";
export * from "./Certificates";
export * from "./AboutTheCompany";
// export * from "./Contacts";
// export * from "./Quality";
// export * from "./Reviews";
